<a href="https://colab.research.google.com/github/sergiocastro85/trabajosPython/blob/main/bfs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

instalar libreria treelib

In [52]:
!pip install treelib

In [76]:
#importar 
from treelib import Tree

In [2]:
import numpy as np

In [5]:
N=5

datos=[1,2,3,4,5,6,0,0,0,7,8,9,10,11,12,13,0,0,14,0,0,0,0,0,0]

matriz=np.array(datos).reshape(N,N)


def expandirnodo(tablero, posactual):
  L=[]
  filactual=np.where(tablero==posactual)[0][0] #.where fila columna
  columnactual=np.where(tablero==posactual)[1][0]#
  
  if filactual!=tablero.shape[0]-1: ##tamaño restamos 1 

    pos=tablero[filactual+1][columnactual] ##me puedo mover a la derecha
    if pos!=0:
      L.append(pos)
  
  if filactual !=0:
    pos=tablero[filactual-1][columnactual] ##me puedo mover a la izquierda
    if pos!=0:
      L.append(pos)

  if columnactual!=tablero.shape[1]-1:
    pos=tablero[filactual][columnactual+1] # me puedo mover abajo
    if pos!=0:
      L.append(pos)
  
  if columnactual!=0:
    pos=tablero[filactual][columnactual-1] #me puedo mover arriba arriba
    if pos!=0:
      L.append(pos)
  
  return L



#pruebassssssssssssssssssss
resultado=expandirnodo(matriz,14)

#expandirnodo(matriz,14)
#print(matriz[0][0])
print(matriz)
print(resultado)

#print(np.where(matriz==11)[0][0])


#l.append(matriz[0:1])


#print(l)

[[ 1  2  3  4  5]
 [ 6  0  0  0  7]
 [ 8  9 10 11 12]
 [13  0  0 14  0]
 [ 0  0  0  0  0]]
[11]


In [77]:
##FUNCION EXPANDIR NODO
N=5

datos=[1,2,3,4,5,6,0,0,0,7,8,9,10,11,12,13,0,0,14,0,0,0,0,0,0]

matriz=np.array(datos).reshape(N,N)


def expandirnodo(tablero, posactual):
  L=[]
  filactual=np.where(tablero==posactual)[0][0] #.where fila columna
  columnactual=np.where(tablero==posactual)[1][0]#
  
  if filactual!=tablero.shape[0]-1: ##tamaño restamos 1 

    pos=tablero[filactual+1][columnactual] ##me puedo mover a la derecha
    if pos!=0:
      L.append(pos)
  
  if filactual !=0:
    pos=tablero[filactual-1][columnactual] ##me puedo mover a la izquierda
    if pos!=0:
      L.append(pos)

  if columnactual!=tablero.shape[1]-1:
    pos=tablero[filactual][columnactual+1] # me puedo mover abajo
    if pos!=0:
      L.append(pos)
  
  if columnactual!=0:
    pos=tablero[filactual][columnactual-1] #me puedo mover arriba arriba
    if pos!=0:
      L.append(pos)
  
  return L

##FUNCION BFS
def bfs (tablero, posinicial, posfinal):
  Q=[]
  T=Tree()
  V=[]
  Q.append(posinicial)
  V.append(posinicial)
  T.create_node(tag=posinicial,identifier=posinicial,data=posinicial)
  while len(Q)!=0:
    pos_actual=Q.pop(0)
    hijos=expandirnodo(tablero,pos_actual)
    for hijo in hijos:
      if hijo not in V:
        T.create_node(tag=hijo,identifier=hijo,parent=pos_actual,data=hijo)
        V.append(hijo)
        Q.append(hijo)
        if hijo==posfinal:
          T.show()
          # for key in T.nodes:
          #   if T.is_ancestor(T.nodes[key].identifier,hijo):
          #     print(T.nodes[key].data)
          # print(posfinal)
          sol = list(T.rsearch(posfinal))
          sol.reverse()
          print(sol)

      
  else:
    print("no Hay Solución")
  

  


In [79]:
bfs(matriz,14,1)

14
└── 11
    ├── 10
    │   └── 9
    │       └── 8
    │           ├── 6
    │           │   └── 1
    │           └── 13
    └── 12
        └── 7
            └── 5
                └── 4
                    └── 3

[14, 11, 10, 9, 8, 6, 1]
no Hay Solución
